# Every key in this this map must be set
sotiApi:
  client_id:
  client_secret:
  username:
  password:
  mobicontrol_host:

logLevel: INFO

image:
  repository: maxrocketinternet/soti-mobicontrol-exporter
  tag: 0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
